# Generated by Django 5.1.5 on 2025-08-20 22:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('userRole', models.CharField(default='Member', max_length=128)),
                ('isRegistered', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.ImageField(blank=True, null=True, upload_to='divisions')),
                ('showRatings', models.BooleanField(default=True)),
                ('shortWords', models.CharField(blank=True, max_length=1024, null=True)),
                ('showVenue', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('titleDesc', models.TextField(blank=True, null=True)),
                ('titleQuote', models.CharField(blank=True, max_length=1024, null=True)),
                ('showUser', models.BooleanField(default=True)),
                ('baseUser', models.CharField(default='Member', max_length=128)),
                ('baseUserModifier', models.CharField(default='Available', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.IntegerField(default=1)),
                ('attendance', models.IntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Data.division')),
            ],
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.IntegerField(default=1)),
                ('attendance', models.IntegerField(default=0)),
                ('reason', models.CharField(default='study/work', max_length=128)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent', to='Data.division')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('highlighted_title', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('shown_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongsLearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date', 'title'],
                'indexes': [models.Index(fields=['date', 'title'], name='Data_songsl_date_a022c5_idx')],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='divisions', to='Data.songslearnt'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='venue_img')),
            ],
            options={
                'ordering': ['-date', 'startTime'],
                'indexes': [models.Index(fields=['-date', 'place'], name='Data_venue_date_37c20e_idx'), models.Index(fields=['role'], name='Data_venue_role_a82161_idx')],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='Data.division')),
                ('venue', models.ManyToManyField(to='Data.venue')),
            ],
        ),
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=128, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('admin_check', models.BooleanField(default=False)),
                ('admin_accept', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_requests', to='Data.division')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_requests', to='Data.venue')),
            ],
        ),
        migrations.CreateModel(
            name='PendingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('showPoster', models.BooleanField(default=True)),
                ('poster', models.FileField(upload_to='pending_activity')),
                ('venue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_activity', to='Data.venue')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='absents',
            field=models.ManyToManyField(related_name='division_absentee', through='Data.Absent', to='Data.venue'),
        ),
        migrations.AddField(
            model_name='division',
            name='attendances',
            field=models.ManyToManyField(related_name='division_attendees', through='Data.Attendance', to='Data.venue'),
        ),
        migrations.AddField(
            model_name='division',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='divisions', through='Data.PendingRequest', to='Data.venue'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data.venue'),
        ),
        migrations.AddField(
            model_name='absent',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent', to='Data.venue'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Data.division')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'division'), name='unique_user_division_rating')],
            },
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['name'], name='Data_divisi_name_d21042_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('name', 'role')},
        ),
    ]
