# Generated by Django 5.1.5 on 2025-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
    ]
