# Generated by Django 5.1.5 on 2025-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='sessions',
            field=models.IntegerField(default=1),
        ),
    ]
