# Generated by Django 5.1.5 on 2025-08-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_division_membercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='memberCount',
        ),
    ]
