# Generated by Django 5.1.5 on 2025-03-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_absent_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sessions',
            field=models.IntegerField(default=1),
        ),
    ]
